### ISSUE TITLE
Run.py fedora error

### ISSUE THREAD

**Issue by happyyo** [plaperdr/blink-docker#8]
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main()
  File "run.py", line 143, in main
    checkInstallation()
  File "run.py", line 38, in checkInstallation
    generateLibrairies()
  File "run.py", line 54, in generateLibrairies
    fedKernel = re.search("kernel-(.{1,20}"+fedoraName+")((?!testing).)*?stable",str(fedSource)).group(1)+".x86_64"
AttributeError: 'NoneType' object has no attribute 'group'

Thats the error am getting when launching for the first time

**Comment by plaperdr** [comment]
Hello! Thank you for your interest in Blink!
My script was looking for the current Linux kernel on Fedora 23 but since it is an old version, it did not find it. I fixed it with commit 149180016038642b89e6aad7a5191c5fca00913c where I updated the Docker containers to Fedora 25 and Ubuntu 16.04 (it was long overdue!). Can you tell me if it works on your end? I've already pushed everything on Docker Hub so you can download the new containers from there if you want.

**Comment by happyyo** [comment]
[happy@localhost blink-docker]$ python3 downloadFromHub.py
Blink Download script

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

happy is not in the sudoers file.  This incident will be reported.
Traceback (most recent call last):
  File "downloadFromHub.py", line 46, in <module>
    main()
  File "downloadFromHub.py", line 23, in main
    if "command not found" in subprocess.check_output(["sudo","docker","info"]).decode():
  File "/usr/lib64/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sudo', 'docker', 'info']' returned non-zero exit status 1



thats what i get when i try downloading from hub
